# accounts_v2.py - 40 nuovi account

ACCOUNTS = [
    {'email': 'sandrominori50+ucupamikowa@gmail.com', 'name': 'ucupamikowa'},
    {'email': 'sandrominori50+ubbmaad@gmail.com', 'name': 'ubbmaad'},
    {'email': 'sandrominori50+unachizaadaa@gmail.com', 'name': 'unachizaadaa'},
    {'email': 'sandrominori50+uzofequ@gmail.com', 'name': 'uzofequ'},
    {'email': 'sandrominori50+ugaglchimulu@gmail.com', 'name': 'ugaglchimulu'},
    {'email': 'sandrominori50+usfnejafi@gmail.com', 'name': 'usfnejafi'},
    {'email': 'sandrominori50+ugaufkokagl@gmail.com', 'name': 'ugaufkokagl'},
    {'email': 'sandrominori50+utuufvo@gmail.com', 'name': 'utuufvo'},
    {'email': 'sandrominori50+umufela@gmail.com', 'name': 'umufela'},
    {'email': 'sandrominori50+uzukimice@gmail.com', 'name': 'uzukimice'},
    {'email': 'sandrominori50+uvatulukofo@gmail.com', 'name': 'uvatulukofo'},
    {'email': 'sandrominori50+ugetrle@gmail.com', 'name': 'ugetrle'},
    {'email': 'sandrominori50+usfkugl@gmail.com', 'name': 'usfkugl'},
    {'email': 'sandrominori50+uzuculo@gmail.com', 'name': 'uzuculo'},
    {'email': 'sandrominori50+uxipgda@gmail.com', 'name': 'uxipgda'},
    {'email': 'sandrominori50+ulidazurzmu@gmail.com', 'name': 'ulidazurzmu'},
    {'email': 'sandrominori50+uncglximo@gmail.com', 'name': 'uncglximo'},
    {'email': 'sandrominori50+ufezusavo@gmail.com', 'name': 'ufezusavo'},
    {'email': 'sandrominori50+ulileaature@gmail.com', 'name': 'ulileaature'},
    {'email': 'sandrominori50+ulorenakino@gmail.com', 'name': 'ulorenakino'},
    {'email': 'sandrominori50+uqulenazusa@gmail.com', 'name': 'uqulenazusa'},
    {'email': 'sandrominori50+ukaramu@gmail.com', 'name': 'ukaramu'},
    {'email': 'sandrominori50+uferalola@gmail.com', 'name': 'uferalola'},
    {'email': 'sandrominori50+ummmarzsarm@gmail.com', 'name': 'ummmarzsarm'},
    {'email': 'sandrominori50+udatrlefe@gmail.com', 'name': 'udatrlefe'},
    {'email': 'sandrominori50+uaakiggzu@gmail.com', 'name': 'uaakiggzu'},
    {'email': 'sandrominori50+uzorzvu@gmail.com', 'name': 'uzorzvu'},
    {'email': 'sandrominori50+uwanepgbo@gmail.com', 'name': 'uwanepgbo'},
    {'email': 'sandrominori50+udioodali@gmail.com', 'name': 'udioodali'},
    {'email': 'sandrominori50+usadiadmobo@gmail.com', 'name': 'usadiadmobo'},
    {'email': 'sandrominori50+ulixire@gmail.com', 'name': 'ulixire'},
    {'email': 'sandrominori50+udiadnczo@gmail.com', 'name': 'udiadnczo'},
    {'email': 'sandrominori50+uzalesagg@gmail.com', 'name': 'uzalesagg'},
    {'email': 'sandrominori50+upabbkafone@gmail.com', 'name': 'upabbkafone'},
    {'email': 'sandrominori50+uramincadkr@gmail.com', 'name': 'uramincadkr'},
    {'email': 'sandrominori50+uganakaeara@gmail.com', 'name': 'uganakaeara'},
    {'email': 'sandrominori50+urerafokrne@gmail.com', 'name': 'urerafokrne'},
    {'email': 'sandrominori50+ufiwakota@gmail.com', 'name': 'ufiwakota'},
    {'email': 'sandrominori50+ukrfojudi@gmail.com', 'name': 'ukrfojudi'},
    {'email': 'sandrominori50+uornewafomo@gmail.com', 'name': 'uornewafomo'},
]

DEFAULT_PASSWORD = "DDnmVV45!!"